# adapted from
# https://github.com/greghendershott/travis-racket/blob/master/.travis.yml
# Thanks Greg!

language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.1.1

matrix:
  fast_finish: true

before_install:
  - git clone https://github.com/mbutterick/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
 - cd ..   # Travis did a cd into the dir. Back up, for the next:
 - raco pkg install --deps search-auto --link pollen
 - raco test -p pollen
