# adapted from
# https://github.com/greghendershott/travis-racket/blob/master/.travis.yml
# Thanks Greg!

language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.0
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.2
    - RACKET_VERSION=6.3
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=6.8
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10
    - RACKET_VERSION=HEAD

# You may want to test against certain versions of Racket, without
# having them count against the overall success/failure.
matrix:
  allow_failures:
    #- env: RACKET_VERSION=HEAD
  # Fast finish: Overall build result is determined as soon as any of
  # its rows have failed, or, all of its rows that aren't allowed to
  # fail have succeeded.
  fast_finish: true

before_install:
  - git clone https://github.com/mbutterick/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
 - cd ..   # Travis did a cd into the dir. Back up, for the next:
  # don't rely on package server for dependencies
 - travis_retry raco pkg install --deps search-auto https://github.com/mbutterick/sugar.git
 - raco test -p sugar
 - travis_retry raco pkg install --deps search-auto https://github.com/mbutterick/txexpr.git
 - raco test -p txexpr
 - travis_retry raco pkg install --deps search-auto --link pollen
 - raco test -p pollen
